---

- name: check pwd
  file:
    path: "{{app_path}}"
    state: directory

- name: prepare nginx
  include: 'nginx.yml'
  become: yes

- name: prepare systemd script
  include: 'systemd.yml'
  become: yes
