---  
- name: install systemd script
  become: true
  template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/rails_{{name}}.service"

- name: reload systemd
  become: true
  command: "systemctl daemon-reload"

- name: enable systemd script
  become: true
  service:
    name: "rails_{{name}}"
    state: started
    enabled: true
