---
- name: application server for haterslist
  hosts: app
  remote_user: production
  vars_files:
    - ../../haterslist_conf/config/vars.yml
  vars:
    app: "{{ apps['haterslist1'] }}"
  tasks:
  - name: install dependences for haterslist
    apt:
      name: "{{item}}"
    with_items:
      - build-essential
      - libmysqlclient-dev
    become: true
  
  roles:
    - role: rails
      deployer: 'production'
      deploy_path: 'apps'
      name: "{{ app['name'] }}"
      hostname: "{{ app['hostname'] }}"
      service: "{{ app['service'] }}"
      config_path: "{{ app['config_path'] }}"

    - role: rvm_io.ruby
      tags: ruby
      rvm1_rubies:
        - "{{ app['ruby'] }}"
      rvm1_user: 'production'
      # ignores after first time
      rvm1_rvm_check_for_updates: False
      rvm1_gpg_keys: ''


- hosts: db
  remote_user: production
  vars_files:
    - ../../haterslist_conf/config/vars.yml
  vars:
    db: "{{ dbs['db1'] }}"
  roles:
    - role: mysql-all
      mysql_root_password: "{{ db['mysql_root_password'] }}"
      databases: "{{ db['databases'] }}"
      users: "{{ db['users'] }}"
